# Generated by Django 5.1.6 on 2025-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='accounts.permission'),
        ),
    ]
