# Generated by Django 5.1.6 on 2025-02-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_role_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
