# Generated by Django 5.2 on 2025-05-19 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_dosage_learnedproduct_dosage_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, max_length=255)),
                ('derived_timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_product_instances', to='core.searchquery')),
                ('source_manual_correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manualcorrection')),
                ('source_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_product_instances', to='core.searchresult')),
            ],
            options={
                'verbose_name_plural': 'Derived Product Instances',
                'ordering': ['search_query', '-derived_timestamp'],
            },
        ),
    ]
